#!/usr/bin/python3

import dp7xx
import random
import time

def main():
  ps = dp7xx.dp7xx("/dev/ttyUSB0")
  print(ps)

  ps.voltage(0.0)
  ps.output(True)

  i = 0
  while True:
    i += 1
    ps.voltage(12.0)
    print(i)
    time.sleep(30.0)
    ps.voltage(0.0)
    time.sleep(2.0)

main()
