#!/usr/bin/python

import dp7xx
import random
import time

def main():
  ps = dp7xx.dp7xx("/dev/ttyUSB0")
  print ps

  ps.voltage(0.0)
  ps.output(True)

  minimal_v = 12.0
  i = 0

  while True:
    i += 1
    ps.voltage(minimal_v)
    t = 0.8 + (random.random() * 0.7)
    print t, i
    time.sleep(t)
    ps.voltage(0.0)
    time.sleep(2.0)

main()
